import type { HomeArticle } from "@/lib/types/article-display";

function img(seed: string): string {
  return `https://picsum.photos/seed/${seed}/640/400`;
}

export const MOCK_ARTICLES: HomeArticle[] = [
  {
    id: "1",
    title: "Senate advances spending bill after late-night negotiations",
    category: "Politics",
    location: "United States",
    imageUrl: img("truth-news-home-1"),
    bias: { left: 20, center: 31, right: 49 },
    sourceCount: 12,
  },
  {
    id: "2",
    title: "Markets rally as inflation data cools faster than expected",
    category: "Business",
    location: "Global",
    imageUrl: img("truth-news-home-2"),
    bias: { left: 18, center: 52, right: 30 },
    sourceCount: 9,
  },
  {
    id: "3",
    title: "Climate summit reaches fragile agreement on emissions targets",
    category: "Environment",
    location: "Europe",
    imageUrl: img("truth-news-home-3"),
    bias: { left: 41, center: 38, right: 21 },
    sourceCount: 15,
  },
  {
    id: "4",
    title: "Tech giants face new antitrust scrutiny in major markets",
    category: "Technology",
    location: "United States",
    imageUrl: img("truth-news-home-4"),
    bias: { left: 33, center: 40, right: 27 },
    sourceCount: 11,
  },
  {
    id: "5",
    title: "World Cup host cities finalize security and transit plans",
    category: "Sports",
    location: "International",
    imageUrl: img("truth-news-home-5"),
    bias: { left: 12, center: 68, right: 20 },
    sourceCount: 7,
  },
  {
    id: "6",
    title: "Health agencies update guidance on seasonal respiratory illness",
    category: "Health",
    location: "United States",
    imageUrl: img("truth-news-home-6"),
    bias: { left: 28, center: 49, right: 23 },
    sourceCount: 10,
  },
  {
    id: "7",
    title: "AI research labs announce joint safety evaluation standards",
    category: "Technology",
    location: "Global",
    imageUrl: img("truth-news-home-7"),
    bias: { left: 35, center: 45, right: 20 },
    sourceCount: 14,
  },
  {
    id: "8",
    title: "Local elections reshape city councils across swing districts",
    category: "Politics",
    location: "United States",
    imageUrl: img("truth-news-home-8"),
    bias: { left: 44, center: 22, right: 34 },
    sourceCount: 8,
  },
  {
    id: "9",
    title: "Extreme weather alerts expand as heat wave intensifies",
    category: "Environment",
    location: "North America",
    imageUrl: img("truth-news-home-9"),
    bias: { left: 38, center: 42, right: 20 },
    sourceCount: 13,
  },
  {
    id: "10",
    title: "Central bank signals cautious path on interest rate cuts",
    category: "Business",
    location: "United States",
    imageUrl: img("truth-news-home-10"),
    bias: { left: 22, center: 48, right: 30 },
    sourceCount: 16,
  },
  {
    id: "11",
    title: "Social platforms roll out new rules for political advertising",
    category: "Media",
    location: "Global",
    imageUrl: img("truth-news-home-11"),
    bias: { left: 30, center: 35, right: 35 },
    sourceCount: 6,
  },
  {
    id: "12",
    title: "Scientists report breakthrough in long-duration battery storage",
    category: "Science",
    location: "Asia",
    imageUrl: img("truth-news-home-12"),
    bias: { left: 25, center: 55, right: 20 },
    sourceCount: 9,
  },
];

export const HOME_CATEGORIES = [
  "World Cup",
  "IPL",
  "Social Media",
  "Business & Markets",
  "Health & Medicine",
  "Soccer",
  "Artificial Intelligence",
  "Arsenal FC",
  "Extreme Weather and Disasters",
] as const;
